### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by el3ctrician** [elmoiv/egybest-downloader#1]
would you please share the source code for the project ?

**Comment by elmoiv** [comment]
I am sorry for not publishing my source code. I did some reverse engineering for Vidstream.to Verification algorithm.
I did a tough work to make this application fast and robust as possible.

If my code is exposed, you know they will re-code their algorithm and break my work.

Sorry again.

**Comment by el3ctrician** [comment]
So you are sharing a binary, without the ability to look at the code and you are not willing to share it to protect your intellectual property ? this is not how open source work and certainly github is not the place to do it ! I was deceived since you hosted your project on github to download it and try it imaging that  you have the source code so not putting any malicious code inside and i was wrong ?! how can i be sure that you are not planting any backdoor to this binary ? should i reverse it ? 
Sure you can tell me that if i don't trust you then simply look away from the project which would make perfect sense if you host it some where else and not on github !
